# vim: ts=4 sw=4 tw=100 et ai si
#
# Example of the yokotool configuration file. It can be placed to '/etc/yokotool.conf',
# '~/.yokotool.conf', or both. Yokotool will first apply the former, and then the latter file.

# Default section is most convenient when you have only one power meter. Use it and you'll be able
# to run yokotool with least command line options.
#   $ yokotool info
[default]
devnode=/dev/wt210
baudrate=9600
pmtype=wt210
connected=[connected device to measure]
read=V,I,P,S,Q,Lambda,Phi,Fv,Fi,Wh,Whp,Whm,Ah,Ahp,Ahm,Vmax,Imax,T,J

# This configuration is used when you run yokotool the following way:
#   $ yokotool wt310 info
[wt310]
devnode=/dev/wt310
pmtype=wt310
connected=[connected device to measure]
read=V,I,P,S,Q,Lambda,Phi,Fv,Fi,Wh

# This configuration is used when you run yokotool the following way:
#   $ yokotool wt210 info
#
# *** REMEMBER to swith Yokogawa WT210 to 488.2 mode! ***
[wt210]
devnode=/dev/wt210
baudrate=9600
pmtype=wt210
connected=[connected device to measure]
read=V,I,P,S,Q,Lambda,Phi,Fv,Fi,Wh,Whp,Whm,Ah,Ahp,Ahm,Vmax,Imax,T,J

[influxdb]
host=influxdb:8086
quiet=yes

[influxdbv2]
host=https://influxdbv2:8086
token=[your token here]
org=[your org here]
cert=/etc/pki/tls/certs/ca-cert.pem
quiet=yes

